channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.10.2
  - numpy==1.26.2
  - pandas==2.1.3
  - psutil==5.9.6
  - scikit-learn==1.3.2
  - scipy==1.11.3
  - xgboost==2.0.2
name: mlflow-env
