stages:
  prepare:
    cmd: python 00_data_preparation.py
    deps:
    - 00_data_preparation.py
    - data/Train.csv
    outs:
    - data/dataset/X_train.parquet
    - data/dataset/y_train.parquet
    - data/dataset/X_val.parquet
    - data/dataset/y_val.parquet
    - data/dataset/X_test.parquet
    - data/dataset/y_test.parquet
  train:
    cmd: python 01_training.py
    deps:
    - 01_training.py
    - data/dataset/X_train.parquet
    - data/dataset/y_train.parquet
    - data/dataset/X_val.parquet
    - data/dataset/y_val.parquet
    params:
    - n_estimators
    - early_stopping_rounds
    - learning_rate
    - max_depth
    - subsample
    - colsample_bytree
    - min_child_weight
    outs:
    - model.json
  evaluate:
    cmd: python 02_evaluation.py
    deps:
    - 02_evaluation.py
    - model.json
    - data/dataset/X_test.parquet
    - data/dataset/y_test.parquet
artifacts:
  mymodel:
    path: model.json
    type: model
    desc: XGBoost
    labels:
    - xgboost
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/images
- dvclive/plots/sklearn/calibration.json:
    template: simple
    x: prob_pred
    y: prob_true
    title: Calibration Curve
    x_label: Mean Predicted Probability
    y_label: Fraction of Positives
- dvclive/plots/sklearn/precision_recall.json:
    template: simple
    x: recall
    y: precision
    title: Precision-Recall Curve
    x_label: Recall
    y_label: Precision
- dvclive/plots/sklearn/roc.json:
    template: simple
    x: fpr
    y: tpr
    title: Receiver operating characteristic (ROC)
    x_label: False Positive Rate
    y_label: True Positive Rate
- dvclive/plots/sklearn/cm.json:
    template: confusion
    x: actual
    y: predicted
    title: Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
